// Code generated by mockery v2.43.1. DO NOT EDIT.

package mocks

import (
	context "context"

	metrics "github.com/maynagashev/go-metrics/internal/contracts/metrics"
	mock "github.com/stretchr/testify/mock"
)

// Storage is an autogenerated mock type for the Storage type
type Storage struct {
	mock.Mock
}

// GetMetrics provides a mock function with given fields: ctx
func (_m *Storage) GetMetrics(ctx context.Context) []metrics.Metric {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetMetrics")
	}

	var r0 []metrics.Metric
	if rf, ok := ret.Get(0).(func(context.Context) []metrics.Metric); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]metrics.Metric)
		}
	}

	return r0
}

// NewStorage creates a new instance of Storage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *Storage {
	mock := &Storage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
